ERROR - 2025-04-27 18:37:30 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#18 {main}
ERROR - 2025-04-27 18:37:30 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#19 {main}
ERROR - 2025-04-27 18:37:56 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#18 {main}
ERROR - 2025-04-27 18:37:56 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#19 {main}
ERROR - 2025-04-27 18:38:12 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#18 {main}
ERROR - 2025-04-27 18:38:12 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#19 {main}
ERROR - 2025-04-27 18:38:22 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#15 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#16 {main}
ERROR - 2025-04-27 18:38:22 --> mysqli_sql_exception: Table 'autest.users' doesn't exist in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\AuTestWin\tests\UserModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#17 {main}
ERROR - 2025-04-27 18:40:35 --> mysqli_sql_exception: Duplicate entry 'ART002' for key 'ref' in C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp1\htdocs\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\xampp1\htdocs\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\xampp1\htdocs\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\xampp1\htdocs\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\AuTestWin\tests\ArticleModelTest.php(50): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#14 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#15 C:\xampp1\htdocs\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#16 C:\xampp1\htdocs\AuTestWin\vendor\bin\phpunit(122): include('C:\\xampp1\\htdoc...')
#17 {main}
ERROR - 2025-04-27 19:42:37 --> mysqli_sql_exception: Duplicata du champ 'ART002' pour la clef 'articles.ref' in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(50): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 19:44:10 --> mysqli_sql_exception: La table 'autest.articles' n'existe pas in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(13): CodeIgniter\BaseModel->findAll()
#7 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testFindAllArticles()
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#18 {main}
ERROR - 2025-04-27 19:44:11 --> mysqli_sql_exception: La table 'autest.articles' n'existe pas in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(27): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testInsertArticle()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 19:44:11 --> mysqli_sql_exception: La table 'autest.articles' n'existe pas in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(40): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 19:44:11 --> mysqli_sql_exception: La table 'autest.users' n'existe pas in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\wamp64\www\tt\AuTestWin\tests\UserModelTest.php(12): CodeIgniter\BaseModel->findAll()
#7 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testFindAllUsers()
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#17 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#18 {main}
ERROR - 2025-04-27 19:44:11 --> mysqli_sql_exception: La table 'autest.users' n'existe pas in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `us...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\UserModelTest.php(21): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\UserModelTest->testInsertUser()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\UserModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 19:44:38 --> mysqli_sql_exception: Duplicata du champ 'ART002' pour la clef 'articles.ref' in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(50): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 19:49:17 --> mysqli_sql_exception: Duplicata du champ 'ART002' pour la clef 'articles.ref' in C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\tt\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\tt\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\tt\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\tt\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\tt\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\tt\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\tt\AuTestWin\tests\ArticleModelTest.php(50): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\tt\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\tt\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\t...')
#19 {main}
ERROR - 2025-04-27 20:18:04 --> mysqli_sql_exception: Error writing file '.\autest\users_634.sdi' (OS errno 28 - No space left on device) in C:\wamp64\www\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('CREATE TABLE `u...', 0)
#1 C:\wamp64\www\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TABLE `u...')
#2 C:\wamp64\www\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE `u...')
#3 C:\wamp64\www\AuTestWin\system\Database\Forge.php(570): CodeIgniter\Database\BaseConnection->query('CREATE TABLE `u...')
#4 C:\wamp64\www\AuTestWin\app\Database\Migrations\2025-04-20-203852_CreateUsersTable.php(27): CodeIgniter\Database\Forge->createTable('users')
#5 C:\wamp64\www\AuTestWin\system\Database\MigrationRunner.php(866): App\Database\Migrations\CreateUsersTable->up()
#6 C:\wamp64\www\AuTestWin\system\Database\MigrationRunner.php(182): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 C:\wamp64\www\AuTestWin\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\wamp64\www\AuTestWin\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\wamp64\www\AuTestWin\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\wamp64\www\AuTestWin\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#11 C:\wamp64\www\AuTestWin\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 C:\wamp64\www\AuTestWin\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}
ERROR - 2025-04-27 20:20:01 --> mysqli_sql_exception: Duplicata du champ 'ART002' pour la clef 'articles.ref' in C:\wamp64\www\AuTestWin\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\wamp64\www\AuTestWin\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `ar...', 0)
#1 C:\wamp64\www\AuTestWin\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ar...')
#2 C:\wamp64\www\AuTestWin\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ar...')
#3 C:\wamp64\www\AuTestWin\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ar...', Array, false)
#4 C:\wamp64\www\AuTestWin\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\AuTestWin\system\BaseModel.php(839): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\AuTestWin\system\Model.php(800): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\wamp64\www\AuTestWin\tests\ArticleModelTest.php(50): CodeIgniter\Model->insert(Array)
#8 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(1656): App\Tests\Models\ArticleModelTest->testUniqueReference()
#9 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(514): PHPUnit\Framework\TestCase->runTest()
#10 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestRunner\TestRunner.php(87): PHPUnit\Framework\TestCase->runBare()
#11 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestCase.php(361): PHPUnit\Framework\TestRunner->run(Object(App\Tests\Models\ArticleModelTest))
#12 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestCase->run()
#13 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#14 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\Framework\TestSuite.php(369): PHPUnit\Framework\TestSuite->run()
#15 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(64): PHPUnit\Framework\TestSuite->run()
#16 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\src\TextUI\Application.php(210): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#17 C:\wamp64\www\AuTestWin\vendor\phpunit\phpunit\phpunit(104): PHPUnit\TextUI\Application->run(Array)
#18 C:\wamp64\www\AuTestWin\vendor\bin\phpunit(122): include('C:\\wamp64\\www\\A...')
#19 {main}
